schema:
  - "http://localhost:5000/graphql"
      # headers:
      #   Authorization: "Bearer YOUR_API_KEY_OR_TOKEN"
      #   x-api-key: "YOUR_API_KEY"
documents: "src/**/*.{ts,tsx}"
extensions:
  codegen:
    config:
      useTypeImports: true
      strictScalars: true
      dedupeFragments: true
      scalars:
        DateTime: "string"
